<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\ValidationException;

class LoginController extends Controller
{
    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function login(Request $request): RedirectResponse
    {
        // Validate credentials
        $credentials = $request->validate([
            'email' => 'required|email',
            'password' => 'required',
        ]);

        $email = $request->input('email');
        $ipAddress = $request->ip();
        $userAgent = $request->userAgent();

        // Use Auth::attempt() which handles session regeneration automatically
        if (Auth::attempt($credentials, $request->filled('remember'))) {
            // Session is automatically regenerated by Auth::attempt()
            $user = Auth::user();

            // Check if account is active
            if ($user->status == 0) {
                Auth::logout();
                
                Log::warning('Login attempt with deactivated account', [
                    'user_id' => $user->id,
                    'email' => $email,
                    'ip_address' => $ipAddress,
                    'user_agent' => $userAgent,
                    'timestamp' => now()->toDateTimeString(),
                ]);

                return redirect()->route('login')
                    ->with('error', 'Your account has been deactivated. Please contact administrator.');
            }

            // Log successful login
            Log::info('User logged in successfully', [
                'user_id' => $user->id,
                'email' => $email,
                'ip_address' => $ipAddress,
                'user_agent' => $userAgent,
                'timestamp' => now()->toDateTimeString(),
            ]);

            // Get user type (raw integer value from database)
            $userType = $user->getRawOriginal('type') ?? $user->getAttributes()['type'] ?? 0;

            // Redirect based on user type
            if ($userType == 1) {
                // Admin user
                return redirect()->route('admin.home')->with('success', 'Welcome back!');
            } elseif ($userType == 2) {
                // Manager user
                return redirect()->route('manager.home')->with('success', 'Welcome back!');
            } else {
                // Regular user
                return redirect()->route('dashboard')->with('success', 'Welcome back!');
            }
        }

        // Authentication failed
        Log::warning('Failed login attempt', [
            'email' => $email,
            'ip_address' => $ipAddress,
            'user_agent' => $userAgent,
            'reason' => 'Invalid credentials',
            'timestamp' => now()->toDateTimeString(),
        ]);

        throw ValidationException::withMessages([
            'email' => 'These credentials do not match our records.',
        ]);
    }

    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function logout(Request $request): RedirectResponse
    {
        $user = Auth::user();
        
        if ($user) {
            Log::info('User logged out', [
                'user_id' => $user->id,
                'email' => $user->email,
                'ip_address' => $request->ip(),
                'user_agent' => $request->userAgent(),
                'timestamp' => now()->toDateTimeString(),
            ]);
        }

        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('login')->with('success', 'You have been logged out successfully.');
    }
}
